### ISSUE TITLE
Is GPLv3 is desired license for this project?

### ISSUE THREAD

**Issue by vovkasm** [erikpoort/react-native-wallet#8]
Hi! Because of GPLv3 license this module can be used only in open source iOS or Android applications. Is it really what author want?

**Comment by erikpoort** [comment]
Hi @vovkasm,

First of all, sorry for the late response!

Secondly, thanks for filing this issue, because I was not aware of this :)
I saw this piece of text on choosealicense.com:
> The GNU GPLv3 also lets people do almost anything they want with your project, except to distribute closed source versions.
Which I interpreted as: They can use it, just not sell it by themselves. I could have read the rest of the text, but got bored ;p

Sooo, all my work is now MIT 🕺 

Hope you secretly used it anyway :)
